"""Application configuration.

All settings are read from environment variables so the dashboard can be
pointed at any ROLE OS Builder output without code changes.
"""

from __future__ import annotations

import os
from functools import lru_cache
from pathlib import Path


class Settings:
    """Runtime configuration for the ROLE OS Dashboard."""

    def __init__(self) -> None:
        self.db_path: Path = Path(
            os.environ.get("ROLE_OS_DB_PATH", "samples/role_os_sample/00_SYSTEM/role_os.db")
        ).resolve()
        # Project Intelligence (Epic 1) uses its own SQLite file, separate from
        # the builder-generated knowledge DB above. It is dashboard-owned:
        # created and migrated automatically on first use, and mutated via the
        # /pi/* API (unlike role_os.db, which is regenerated by builder.py).
        self.projects_db_path: Path = Path(
            os.environ.get(
                "ROLE_OS_PROJECTS_DB_PATH",
                "samples/role_os_sample/00_SYSTEM/role_os_projects.db",
            )
        ).resolve()
        # AI Advisor (Epic 2) also owns its own SQLite file, separate from
        # both the knowledge DB and the projects DB, so recommendation data
        # never touches either — it only ever reads from them.
        self.advisor_db_path: Path = Path(
            os.environ.get(
                "ROLE_OS_ADVISOR_DB_PATH",
                "samples/role_os_sample/00_SYSTEM/role_os_advisor.db",
            )
        ).resolve()
        # ChatGPT Conversation Importer (Sprint B1) also owns its own SQLite
        # file, separate from every other domain's store. It only holds
        # normalized conversation metadata/content and import run history —
        # no AI extraction, project matching, or graph data lives here.
        self.imports_db_path: Path = Path(
            os.environ.get(
                "ROLE_OS_IMPORTS_DB_PATH",
                "samples/role_os_sample/00_SYSTEM/role_os_imports.db",
            )
        ).resolve()
        # Knowledge Extraction (Sprint 4) also owns its own SQLite file,
        # separate from every other domain's store. It holds extracted
        # objects (Project, Person, Task, Decision, Idea, Document, Asset)
        # and extraction run history, derived from imports_db_path's
        # conversations but never written back into that database.
        self.extraction_db_path: Path = Path(
            os.environ.get(
                "ROLE_OS_EXTRACTION_DB_PATH",
                "samples/role_os_sample/00_SYSTEM/role_os_extraction.db",
            )
        ).resolve()
        self.app_name: str = "ROLE OS"
        self.app_version: str = "1.1.0"
        self.license: str = "Proprietary"
        self.base_dir: Path = Path(__file__).resolve().parent
        self.static_dir: Path = self.base_dir / "static"
        self.templates_dir: Path = self.base_dir / "templates"
        self.repo_root: Path = self.base_dir.parent.parent
        # Settings (Sprint 8): both env-var driven, same pattern as every
        # path above -- no new persistence, just two more optional
        # environment variables. `default_import_path` has no behavior
        # wired to it yet (nothing currently pre-fills an import dialog
        # with it); it exists so the Settings page has something honest
        # to display instead of a placeholder. `search_result_limit` *is*
        # wired in: it's the Advisor Search API's default `limit` when the
        # caller doesn't specify one.
        self.default_import_path: str = os.environ.get("ROLE_OS_DEFAULT_IMPORT_PATH", "")
        self.search_result_limit: int = int(os.environ.get("ROLE_OS_SEARCH_RESULT_LIMIT", "100"))
        # Daily Session (ROLE OS Dashboard MVP) also owns its own SQLite file,
        # separate from every other domain's store. Unlike the sample-seeded
        # paths above, its default lives under the repo's git-ignored `var/`
        # directory (not `samples/`) because session data is real personal
        # data the user generates by using the dashboard, not a checked-in
        # fixture — it must never default into a path `.gitignore` allows
        # back into version control.
        self.session_db_path: Path = Path(
            os.environ.get("ROLE_OS_SESSION_DB_PATH", "var/role_os_dashboard/role_os_session.db")
        ).resolve()
        # Optional path to an Obsidian vault's Daily Notes folder, used only
        # to offer writing the generated daily Markdown record directly to
        # disk. Empty by default -- never hardcoded, never committed, and
        # only ever read from this environment variable (the same pattern
        # every other path in this file already uses; this repo has no
        # `.env` file convention to accidentally commit it into either).
        self.obsidian_daily_notes_dir: str = os.environ.get("ROLE_OS_OBSIDIAN_DAILY_NOTES_DIR", "")
        # Optional path to the ROLE Ecosystem's own DECISION_LOG.md, read
        # read-only to surface recent ecosystem decisions on the Session
        # page. Empty by default: cross-repository reading is opt-in, never
        # assumed, and the adapter falls back to documented sample data when
        # this is unset or the file can't be read (see app/session/decisions_adapter.py).
        self.ecosystem_decision_log_path: str = os.environ.get(
            "ROLE_OS_ECOSYSTEM_DECISION_LOG_PATH", ""
        )
        # Workspace Adoption (Discovery Engine Sprint 2) also owns its own
        # SQLite file, separate from every other domain's store. It holds
        # exactly two things: a cached copy of the last Discovery Engine
        # scan (so the Workspace page doesn't re-scan the filesystem on
        # every request) and the small user-editable overlay per adopted
        # folder (priority/business value/status/tags/notes/ignore flag).
        # It never stores name/git/health/classification/etc -- those are
        # always read fresh from the cached scan, matching this feature's
        # "filesystem is the source of truth, do not duplicate metadata"
        # requirement. Lives under `var/`, like `session_db_path`, because
        # it holds real personal data generated by using the dashboard.
        self.workspace_db_path: Path = Path(
            os.environ.get(
                "ROLE_OS_WORKSPACE_DB_PATH", "var/role_os_dashboard/role_os_workspace.db"
            )
        ).resolve()
        # The folder the Discovery Engine scans by default. Defaults to this
        # checkout's own parent directory, which is the real project root
        # validated in Sprint 1 (`1 - IA PROJECTS`) when running from this
        # repo's normal location -- not hardcoded as a literal string, so it
        # never bakes a username/path into source. Always overridable, and
        # the Rescan endpoint also accepts an explicit root per call.
        self.discovery_root: str = os.environ.get(
            "ROLE_OS_DISCOVERY_ROOT", str(self.repo_root.parent)
        )
        # Sprint 3 (Project Boundary): optional extra exclusions layered on
        # top of the Discovery Engine's own default exclusion list (see
        # `app/discovery/boundary/exclusions_config.json`). A comma-
        # separated list of folder *names or glob patterns* -- never an
        # absolute path, so this can never bake this machine's directory
        # structure into a committed config the way a path would.
        raw_extra_exclusions = os.environ.get("ROLE_OS_DISCOVERY_EXTRA_EXCLUSIONS", "")
        self.discovery_extra_exclusions: list[str] = [
            item.strip() for item in raw_extra_exclusions.split(",") if item.strip()
        ]
        # Assets OS (Sprint C4) also owns its own SQLite file, separate
        # from every other domain's store. It holds exactly two things:
        # `asset_cache` (path+mtime+size-keyed dimensions/hash, so a
        # rescan never re-parses or re-hashes an unchanged file) and
        # `asset_overrides` (user-set reusable/category/favorite flags).
        # Neither ever contains file bytes or duplicates project metadata
        # -- the filesystem stays the single source of truth. Lives under
        # `var/`, like `workspace_db_path`, because it holds real data
        # generated by using the dashboard, not a checked-in fixture.
        self.assets_db_path: Path = Path(
            os.environ.get("ROLE_OS_ASSETS_DB_PATH", "var/role_os_dashboard/role_os_assets.db")
        ).resolve()
        # Cached, resized preview thumbnails -- generated images derived
        # from scanned assets, never a copy/move/edit of the originals
        # themselves (the brief's explicit "never copy, move, rename,
        # edit, or delete scanned assets" rule). Always safe to delete
        # entirely; regenerated on next preview request.
        self.asset_thumbnail_cache_dir: Path = Path(
            os.environ.get(
                "ROLE_OS_ASSET_THUMBNAIL_CACHE_DIR", "var/role_os_dashboard/asset_thumbnails"
            )
        ).resolve()
        # Project Ecosystem Engine (Sprint C8): a small overlay table for
        # manual relationship overrides (dismiss a false-positive detected
        # relationship, or confirm/add one by hand) -- never the
        # relationships themselves, which are always recomputed fresh from
        # ProjectContext/Assets/Knowledge/PI dependencies, the same
        # "detector output, not a stored graph" rule every other domain's
        # `var/`-relative db follows.
        self.ecosystem_db_path: Path = Path(
            os.environ.get(
                "ROLE_OS_ECOSYSTEM_DB_PATH", "var/role_os_dashboard/role_os_ecosystem.db"
            )
        ).resolve()


@lru_cache
def get_settings() -> Settings:
    return Settings()
