"""Application configuration.

All settings are read from environment variables so the dashboard can be
pointed at any ROLE OS Builder output without code changes.
"""

from __future__ import annotations

import os
from functools import lru_cache
from pathlib import Path


class Settings:
    """Runtime configuration for the ROLE OS Dashboard."""

    def __init__(self) -> None:
        self.db_path: Path = Path(
            os.environ.get("ROLE_OS_DB_PATH", "samples/role_os_sample/00_SYSTEM/role_os.db")
        ).resolve()
        # Project Intelligence (Epic 1) uses its own SQLite file, separate from
        # the builder-generated knowledge DB above. It is dashboard-owned:
        # created and migrated automatically on first use, and mutated via the
        # /pi/* API (unlike role_os.db, which is regenerated by builder.py).
        self.projects_db_path: Path = Path(
            os.environ.get(
                "ROLE_OS_PROJECTS_DB_PATH",
                "samples/role_os_sample/00_SYSTEM/role_os_projects.db",
            )
        ).resolve()
        # AI Advisor (Epic 2) also owns its own SQLite file, separate from
        # both the knowledge DB and the projects DB, so recommendation data
        # never touches either — it only ever reads from them.
        self.advisor_db_path: Path = Path(
            os.environ.get(
                "ROLE_OS_ADVISOR_DB_PATH",
                "samples/role_os_sample/00_SYSTEM/role_os_advisor.db",
            )
        ).resolve()
        self.app_name: str = "ROLE OS Dashboard"
        self.app_version: str = "0.1.0"
        self.base_dir: Path = Path(__file__).resolve().parent
        self.static_dir: Path = self.base_dir / "static"
        self.templates_dir: Path = self.base_dir / "templates"


@lru_cache
def get_settings() -> Settings:
    return Settings()
