"""Application configuration.

All settings are read from environment variables so the dashboard can be
pointed at any ROLE OS Builder output without code changes.
"""

from __future__ import annotations

import os
from functools import lru_cache
from pathlib import Path


class Settings:
    """Runtime configuration for the ROLE OS Dashboard."""

    def __init__(self) -> None:
        self.db_path: Path = Path(
            os.environ.get("ROLE_OS_DB_PATH", "samples/role_os_sample/00_SYSTEM/role_os.db")
        ).resolve()
        # Project Intelligence (Epic 1) uses its own SQLite file, separate from
        # the builder-generated knowledge DB above. It is dashboard-owned:
        # created and migrated automatically on first use, and mutated via the
        # /pi/* API (unlike role_os.db, which is regenerated by builder.py).
        self.projects_db_path: Path = Path(
            os.environ.get(
                "ROLE_OS_PROJECTS_DB_PATH",
                "samples/role_os_sample/00_SYSTEM/role_os_projects.db",
            )
        ).resolve()
        # AI Advisor (Epic 2) also owns its own SQLite file, separate from
        # both the knowledge DB and the projects DB, so recommendation data
        # never touches either — it only ever reads from them.
        self.advisor_db_path: Path = Path(
            os.environ.get(
                "ROLE_OS_ADVISOR_DB_PATH",
                "samples/role_os_sample/00_SYSTEM/role_os_advisor.db",
            )
        ).resolve()
        # ChatGPT Conversation Importer (Sprint B1) also owns its own SQLite
        # file, separate from every other domain's store. It only holds
        # normalized conversation metadata/content and import run history —
        # no AI extraction, project matching, or graph data lives here.
        self.imports_db_path: Path = Path(
            os.environ.get(
                "ROLE_OS_IMPORTS_DB_PATH",
                "samples/role_os_sample/00_SYSTEM/role_os_imports.db",
            )
        ).resolve()
        # Knowledge Extraction (Sprint 4) also owns its own SQLite file,
        # separate from every other domain's store. It holds extracted
        # objects (Project, Person, Task, Decision, Idea, Document, Asset)
        # and extraction run history, derived from imports_db_path's
        # conversations but never written back into that database.
        self.extraction_db_path: Path = Path(
            os.environ.get(
                "ROLE_OS_EXTRACTION_DB_PATH",
                "samples/role_os_sample/00_SYSTEM/role_os_extraction.db",
            )
        ).resolve()
        self.app_name: str = "ROLE OS"
        self.app_version: str = "1.1.0"
        self.license: str = "Proprietary"
        self.base_dir: Path = Path(__file__).resolve().parent
        self.static_dir: Path = self.base_dir / "static"
        self.templates_dir: Path = self.base_dir / "templates"
        self.repo_root: Path = self.base_dir.parent.parent
        # Settings (Sprint 8): both env-var driven, same pattern as every
        # path above -- no new persistence, just two more optional
        # environment variables. `default_import_path` has no behavior
        # wired to it yet (nothing currently pre-fills an import dialog
        # with it); it exists so the Settings page has something honest
        # to display instead of a placeholder. `search_result_limit` *is*
        # wired in: it's the Advisor Search API's default `limit` when the
        # caller doesn't specify one.
        self.default_import_path: str = os.environ.get("ROLE_OS_DEFAULT_IMPORT_PATH", "")
        self.search_result_limit: int = int(os.environ.get("ROLE_OS_SEARCH_RESULT_LIMIT", "100"))
        # Daily Session (ROLE OS Dashboard MVP) also owns its own SQLite file,
        # separate from every other domain's store. Unlike the sample-seeded
        # paths above, its default lives under the repo's git-ignored `var/`
        # directory (not `samples/`) because session data is real personal
        # data the user generates by using the dashboard, not a checked-in
        # fixture — it must never default into a path `.gitignore` allows
        # back into version control.
        self.session_db_path: Path = Path(
            os.environ.get("ROLE_OS_SESSION_DB_PATH", "var/role_os_dashboard/role_os_session.db")
        ).resolve()
        # Optional path to an Obsidian vault's Daily Notes folder, used only
        # to offer writing the generated daily Markdown record directly to
        # disk. Empty by default -- never hardcoded, never committed, and
        # only ever read from this environment variable (the same pattern
        # every other path in this file already uses; this repo has no
        # `.env` file convention to accidentally commit it into either).
        self.obsidian_daily_notes_dir: str = os.environ.get("ROLE_OS_OBSIDIAN_DAILY_NOTES_DIR", "")
        # Optional path to the ROLE Ecosystem's own DECISION_LOG.md, read
        # read-only to surface recent ecosystem decisions on the Session
        # page. Empty by default: cross-repository reading is opt-in, never
        # assumed, and the adapter falls back to documented sample data when
        # this is unset or the file can't be read (see app/session/decisions_adapter.py).
        self.ecosystem_decision_log_path: str = os.environ.get(
            "ROLE_OS_ECOSYSTEM_DECISION_LOG_PATH", ""
        )


@lru_cache
def get_settings() -> Settings:
    return Settings()
