"""External managed work (Role OS 2.0, Phase 3 Task 5 -- universal ingestion).

Useful work does not always have a local folder: a Claude Web or ChatGPT
project, a Chrome bookmarklet, a GitHub-only repository, a web tool. This
module lets Role record such work *by hand* as a managed-work row in the
existing `adopted_projects` overlay -- no new database, no new entity:

* WHAT it is      -> `kind` (project | tool), P3.2
* WHOSE work      -> `domain` / `client_name`, P3.2
* WHERE it lives  -> `source` (claude_web, chatgpt, chrome_bookmark, ...)
* HOW to open it  -> `external_url` and/or `external_reference`

`adopted_projects.root_path` is the table's identity column (UNIQUE NOT
NULL). An external row stores an opaque key there (`external:<uuid>`) --
generated by Role OS, never shown or used as a filesystem path. Every
Workspace consumer sees `root_path = None` for external items (see
`service._merge`), which the existing "no local root" branches already
handle (Resume Work routes to a web assistant, no file reads, no asset
walk, no Claude Code launch).

Security boundaries: URLs are user-provided navigation pointers only --
never fetched, never scraped, never proof Role OS can read the content.
Only `http(s)` URLs are accepted (no `javascript:` bookmarklet code, no
`file:`/`data:`), embedded credentials (`user:pass@`) are rejected, and a
reference may not be bookmarklet source code. Nothing reads Chrome,
browser profiles, cookies, or tokens.
"""

from __future__ import annotations

import uuid
from typing import Any
from urllib.parse import urlsplit

from app.workspace import classification

EXTERNAL_KEY_PREFIX = "external:"
MAX_NAME = 200
MAX_URL = 2048
MAX_REFERENCE = 500
MAX_TEXT = 4000


def new_external_key() -> str:
    return EXTERNAL_KEY_PREFIX + uuid.uuid4().hex


def is_external_key(root_path: str | None) -> bool:
    return bool(root_path) and str(root_path).startswith(EXTERNAL_KEY_PREFIX)


def normalize_name(value: str | None) -> str:
    cleaned = " ".join(str(value or "").split())
    if not cleaned:
        raise ValueError("name is required")
    if len(cleaned) > MAX_NAME:
        raise ValueError(f"name must be at most {MAX_NAME} characters")
    return cleaned


def normalize_url(value: str | None) -> str | None:
    """Blank -> None. Otherwise an absolute http(s) URL with a host and no
    embedded credentials. Purely syntactic -- no network access."""
    cleaned = str(value or "").strip()
    if not cleaned:
        return None
    if len(cleaned) > MAX_URL:
        raise ValueError(f"URL must be at most {MAX_URL} characters")
    if any(ch.isspace() for ch in cleaned):
        raise ValueError("URL must not contain spaces")
    parts = urlsplit(cleaned)
    if parts.scheme.lower() not in ("http", "https") or not parts.hostname:
        raise ValueError(
            "URL must be a full http(s) link, e.g. https://claude.ai/project/... "
            "(bookmarklet 'javascript:' code is not stored -- describe where the bookmark is instead)"
        )
    if parts.username or parts.password:
        raise ValueError("URL must not contain a username or password")
    return cleaned


def normalize_reference(value: str | None) -> str | None:
    """Free-text "where/how to find it" (e.g. "Chrome bookmarks bar >
    Kontoor > FS Quick Actions"). Not a place for code or secrets."""
    cleaned = " ".join(str(value or "").split())
    if not cleaned:
        return None
    if len(cleaned) > MAX_REFERENCE:
        raise ValueError(f"reference must be at most {MAX_REFERENCE} characters")
    if cleaned.lower().startswith("javascript:"):
        raise ValueError(
            "reference must describe where the tool lives, not contain bookmarklet code"
        )
    return cleaned


def normalize_text(value: str | None, field: str) -> str | None:
    cleaned = str(value or "").strip()
    if not cleaned:
        return None
    if len(cleaned) > MAX_TEXT:
        raise ValueError(f"{field} must be at most {MAX_TEXT} characters")
    return cleaned


def validate_external_work(payload: dict[str, Any]) -> dict[str, Any]:
    """Normalizes + validates one Add External Work submission. Raises
    `ValueError` with a human message; never guesses a missing value."""
    domain = classification.normalize_domain(payload.get("domain"))
    client_name = classification.normalize_client_name(payload.get("client_name"))
    classification.check_client_for_domain(domain, client_name)
    status = " ".join(str(payload.get("status") or "active").split()).lower()
    priority = " ".join(str(payload.get("priority") or "medium").split()).lower()
    return {
        "name": normalize_name(payload.get("name")),
        "kind": classification.normalize_kind(payload.get("kind")),
        "domain": domain,
        "client_name": client_name,
        "source": classification.normalize_source(payload.get("source"), allow_local=False),
        "external_url": normalize_url(payload.get("external_url")),
        "external_reference": normalize_reference(payload.get("external_reference")),
        "status": status,
        "priority": priority,
        "purpose": normalize_text(payload.get("purpose"), "purpose"),
        "next_action": normalize_text(payload.get("next_action"), "next action"),
    }


def as_workspace_project(overlay: dict[str, Any]) -> dict[str, Any]:
    """The discovery-shaped record an external overlay row contributes to
    `service._cached_projects()` -- honest defaults only (no health score,
    no git, no guessed classification or activity)."""
    return {
        "root_path": overlay["root_path"],
        "name": overlay.get("display_name") or "Untitled external work",
        "depth": 1,
        "parent_path": None,
        "git": {},
        "classification": "External Work",
        "confidence_score": 0.0,
        "health_score": None,
        "recommendation": "Managed manually -- no local folder to analyze",
        "last_modified": None,
        "item_kind": "project",
        "is_top_level_project": True,
        "project_root_id": None,
        "hierarchy_depth": 0,
        "boundary_evidence": ["external managed work added by Role (no local folder)"],
        "registration_source": "external",
    }
